name: bbs_state
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  mobx: ^2.2.0
  # linkify: ^5.0.0
  # charset: ^2.0.1
  # stash: ^5.0.1
  # stash_sembast: ^5.0.1
  # stash_sembast_web: ^5.0.0
  universal_io: ^2.2.2
  appwrite: ^9.0.1
  sembast: ^3.5.0+1
  path_provider: ^2.1.1
  filesize: ^2.0.1

  model:
    # git:
    #   url: https://github.com/taki-0010/bbs_model.git
      # url: git@github.com:taki-0010/bbs_model.git
  # model:
    path: ../model
  data:
    # git:
    #   url: https://github.com/taki-0010/bbs_data.git
      # url: git@github.com:taki-0010/bbs_data.git

  # data:
    path: ../data

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0